OBJ = A B C D E F

A: A.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@
B: B.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@

C: C.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@

D: D.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@

E: E.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@

F: F.cpp
	g++ -std=c++11 $@.cpp -o $@
	./$@

.phony:
	clean
	
clean:
	rm $(OBJ)
